# Generated by Django 5.2 on 2025-04-10 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0005_rename_name_candidate_full_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=15)),
                ('description', models.TextField(max_length=250)),
                ('currency', models.CharField(choices=[('UGX', 'Ugandan Shilling'), ('KES', 'Kenyan Shilling'), ('TZS', 'Tanzanian Shilling')], default='UGX', max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('email', models.EmailField(max_length=254)),
                ('country', models.CharField(max_length=100)),
                ('valid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vote_count', models.IntegerField()),
                ('is_valid', models.BooleanField(default=False)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='events.candidate')),
            ],
        ),
    ]
