# Generated by Django 5.2 on 2025-04-10 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='is_valid',
        ),
        migrations.AddField(
            model_name='payment',
            name='merchant_reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='order_tracking_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='vote_count',
            field=models.IntegerField(default=0),
        ),
    ]
