# Generated by Django 5.2 on 2025-04-07 21:07

import mdeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_rename_is_virtual_event_is_done_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='content',
            field=mdeditor.fields.MDTextField(default='django'),
        ),
    ]
