# Generated by Django 5.2 on 2025-04-07 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='name',
            new_name='full_name',
        ),
        migrations.AlterUniqueTogether(
            name='candidate',
            unique_together={('event', 'full_name')},
        ),
        migrations.AddField(
            model_name='candidate',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
