# Generated by Django 5.2 on 2025-04-05 11:11

import mdeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
        ('events', '0002_remove_event_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='categories',
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=mdeditor.fields.MDTextField(),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
